[project]
name = "jax-flax-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flax>=0.10.1",
    "jax>=0.4.35",
    "jupyterlab>=4.3.0",
]
